use std::fs::{read_dir, write};

const USER_BIN_DIR: &str = "./target/riscv64gc-unknown-none-elf/release";
// use std::fs::{read_dir,File};
fn main() -> std::io::Result<()> {
    // 内核链接脚本（绝对路径，避免与 user 包的 rustflags 冲突）
    println!(
        "cargo:rustc-link-arg=-T{}/linker.ld",
        std::env::var("CARGO_MANIFEST_DIR").unwrap()
    );
    // 内核自身产物名（cargo 会把内核二进制写到同一个 release 目录）
    let kernel_name = std::env::var("CARGO_PKG_NAME").unwrap_or_default();
    // cargo clean 后 release 目录可能不存在：生成空 APPS 让内核可编译，
    // 等 user 重新 build 后 build.rs 会自动重跑并生成真实 APPS
    let bins: Vec<_> = match read_dir(USER_BIN_DIR) {
        Ok(entries) => entries
            .filter_map(|entry| {
                let entry = entry.ok()?;
                let path = entry.path();
                let name = path.file_name()?.to_str()?.to_string();
                if path.extension().is_none()
                    && path.is_file()
                    && !name.starts_with(".")
                    && name != kernel_name
                {
                    Some(path)
                } else {
                    None
                }
            })
            .collect(),
        Err(_) => {
            println!(
                "cargo:warning=user 程序目录不存在（{USER_BIN_DIR}），\
                 先执行 `cargo build -p user_lib --release`；\
                 当前生成空 APPS（NUM_APPS=0）"
            );
            write_empty_link_app()?;
            return Ok(());
        }
    };
    if bins.is_empty() {
        println!(
            "cargo:warning=no user ELF found in {USER_BIN_DIR}, \
             run `cargo build -p user_lib --release` first!"
        );
    }
    let app_num = bins.len();
    for bin in &bins {
        // 只在 user 产物变化时重跑 build.rs（避免每次编译都重新生成 .bin 触发内核重编）
        println!("cargo:rerun-if-changed={}", bin.to_str().unwrap());
        let path_elf = bin.to_str().unwrap();
        let path_bin = format!("{path_elf}.bin");
        std::process::Command::new("rust-objcopy")
            .args([
                "--binary-architecture=riscv64",
                "--strip-all",
                "-O",
                "binary",
                path_elf,
                &path_bin,
            ])
            .status()
            .expect("failed to turn elf files into binary files");
    }
    let apps: Vec<_> = bins
        .iter()
        //.map(|path| path.file_name().unwrap().to_str().unwrap().to_owned() + ".bin")
        .filter_map(|path| Some(path.file_name()?.to_str()?.to_owned()))
        .collect();
    let app_names = apps
        .iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(",");
    let apps_str = apps
        .iter()
        .enumerate()
        .map(|(i, _)| format!("APP_{}", i))
        .collect::<Vec<_>>()
        .join(",");
    let mut content = format!(
        r#"// Auto-generated by build.rs
#[allow(unused)]
use crate::println;
pub static NUM_APPS: usize = {app_num};     
        "#,
    );
    for (i, app) in apps.iter().enumerate() {
        content += &format!(
            r#"
static APP_{i}: &[u8] = include_bytes!("../{USER_BIN_DIR}/{app}.bin");"#
        );
    }
    content += &format!(
        r#"
pub static APPS: &[&[u8]] = &[{apps_str}];"#
    );
    content += &format!(
        r#"
pub static APP_NAMES: &[&str] = &[{app_names}];"#
    );
    write("src/link_app.rs", content)?;
    //println!("cargo:warning={:?}",bins);
    Ok(())
}

/// 生成空的 link_app.rs（release 目录不存在时用，保证内核可编译）
fn write_empty_link_app() -> std::io::Result<()> {
    write(
        "src/link_app.rs",
        r#"// Auto-generated by build.rs (empty: no user binaries found)
#[allow(unused)]
use crate::println;
pub static NUM_APPS: usize = 0;
pub static APPS: &[&[u8]] = &[];
pub static APP_NAMES: &[&str] = &[];
"#,
    )
}
