use std::fs::{read_dir, write};

const USER_BIN_DIR: &str = "./target/riscv64gc-unknown-none-elf/release";
// use std::fs::{read_dir,File};
fn main() -> std::io::Result<()> {
    let bins: Vec<_> = read_dir(USER_BIN_DIR)?
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.extension().is_none()
                && path.is_file()
                && !path.file_name()?.to_str()?.starts_with(".")
            {
                Some(path)
            } else {
                None
            }
        })
        .collect();
    for bin in &bins {
        let path_elf = bin.to_str().unwrap();
        let path_bin = format!("{path_elf}.bin");
        std::process::Command::new("rust-objcopy")
            .args([
                "--binary-architecture=riscv64",
                "--strip-all",
                "-O",
                "binary",
                path_elf,
                &path_bin,
            ])
            .status()
            .expect("failed to turn elf files into binary files");
    }
    let apps: Vec<_> = bins
        .iter()
        //.map(|path| path.file_name().unwrap().to_str().unwrap().to_owned() + ".bin")
        .filter_map(|path| Some(path.file_name()?.to_str()?.to_owned() + ".bin"))
        .collect();

    let mut content = format!(
        r#"// Auto-generated by build.rs
#[allow(unused)]
use crate::println;
pub static NUM_APPS: usize = {0};     
        "#,
        bins.len()
    );
    for (i, app) in apps.iter().enumerate() {
        content = content
            + &format!(
                r#"
static APP_{i}: &[u8] = include_bytes!("../{USER_BIN_DIR}/{app}");"#
            );
    }
    let apps_str = apps
        .iter()
        .enumerate()
        .map(|(i, _)| format!("APP_{}", i))
        .collect::<Vec<_>>()
        .join(",");
    content = content
        + &format!(
            r#"
pub static APPS: &[&[u8]] = &[{apps_str}];"#
        );
    write("src/link_app.rs", content)?;
    //println!("cargo:warning={:?}",bins);
    Ok(())
}
