// Auto-generated by build.rs
#[allow(unused)]
use crate::println;
pub static NUM_APPS: usize = 4;

static APP_0: &[u8] =
    include_bytes!(".././target/riscv64gc-unknown-none-elf/release/bad_address.bin");
static APP_1: &[u8] =
    include_bytes!(".././target/riscv64gc-unknown-none-elf/release/bad_register.bin");
static APP_2: &[u8] = include_bytes!(".././target/riscv64gc-unknown-none-elf/release/hello.bin");
static APP_3: &[u8] =
    include_bytes!(".././target/riscv64gc-unknown-none-elf/release/bad_instructions.bin");
pub static APPS: &[&[u8]] = &[APP_0, APP_1, APP_2, APP_3];
