
// Auto-generated by build.rs
#[allow(unused)]
use crate::println;
pub static NUM_APPS: usize = 1;     
        
static APP_0: &[u8] = include_bytes!(".././target/riscv64gc-unknown-none-elf/release/hello.bin");
pub static APPS: &[&[u8]] = &[APP_0];